services:
  some-clickhouse-server:
    image: clickhouse/clickhouse-server:22.11.2 
    ports:
      - "8123:8123"
      - "9001:9000"
    volumes:
      # - ./data:/var/lib/clickhouse
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql