version: "3"
services:
 
  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.2
    ports:
      - 3000:3000
    networks:
      - elastic_network
 
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node      
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic_network

  kibana:
    image: kibana
    container_name: kibana:7.17.7
    ports:
      - "5601:5601"
    networks:
      - elastic_network
    depends_on:
      - elasticsearch

networks:
  elastic_network:
    name: "elastic"
    driver: bridge